#!/bin/sh

# Nvidia crap
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

# Why do I have to set dpi in so many places?! QQ
xrandr --dpi 96

# If extra monitor is connected
xrandr | grep VGA | grep " connected "
if [ $? -eq 0 ]; then
    xrandr --output LVDS-1-0 --auto --output VGA-1-0 --right-of LVDS-1-0
fi

# Default crap
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Isn't this handled by systemd?
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# My fav vm
exec i3
